function [optsNew] = optsForSha1(optsOld)
%OPTSFORSHA1 Returns options that are suitable for computing SHA1
% Removes certain options that should not influence the SHA1
% (e.g. encoding does not depend on the model parameters or dir names)
optsNew = rmfieldf(optsOld, ...
  {'C', 'C1', 'C2', 'kernel', 'mtlPrefix', ...
  'perfMeasure', 'dataDir', 'experimentsDir', 'datasetDir', ...
  'cacheDir', 'resultDir', 'imdbPath', 'encoderPath', 'diaryPath', ...
  'trnKernelPath', 'tstKernelPath', ...
  'resultPath', 'modelPath', 'modelSelectionPath', ...
  'mtlResultPath', 'mtlModelPath', 'mtlModelSelectionPath', ...
  'stlResultPath', 'stlModelPath', 'stlModelSelectionPath'}) ;
